/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/park.glb --types
*/

import { useGLTF } from "@react-three/drei";
import type React from "react";
import type * as THREE from "three";
import type { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    field: THREE.Mesh;
    Sphere003_1: THREE.Mesh;
    Sphere003_2: THREE.Mesh;
    Sphere005: THREE.Mesh;
    Sphere005_1: THREE.Mesh;
    Sphere006: THREE.Mesh;
    Sphere006_1: THREE.Mesh;
    Sphere007: THREE.Mesh;
    Sphere007_1: THREE.Mesh;
    Sphere008: THREE.Mesh;
    Sphere008_1: THREE.Mesh;
    wood_poles: THREE.Mesh;
    Sphere009: THREE.Mesh;
    Sphere009_1: THREE.Mesh;
    Sphere010: THREE.Mesh;
    Sphere010_1: THREE.Mesh;
    Sphere011: THREE.Mesh;
    Sphere011_1: THREE.Mesh;
    Sphere012: THREE.Mesh;
    Sphere012_1: THREE.Mesh;
    Sphere013: THREE.Mesh;
    Sphere013_1: THREE.Mesh;
    Sphere014: THREE.Mesh;
    Sphere014_1: THREE.Mesh;
    Cylinder025: THREE.Mesh;
    Cylinder025_1: THREE.Mesh;
    Torus: THREE.Mesh;
    Torus001: THREE.Mesh;
    Torus002: THREE.Mesh;
    Cube: THREE.Mesh;
    Plane: THREE.Mesh;
    Sphere: THREE.Mesh;
    Sphere020: THREE.Mesh;
    Sphere001: THREE.Mesh;
    Sphere002: THREE.Mesh;
    Sphere003: THREE.Mesh;
    Sphere004: THREE.Mesh;
  };
  materials: {
    field: THREE.MeshStandardMaterial;
    leaf: THREE.MeshStandardMaterial;
    wood_black: THREE.MeshStandardMaterial;
    ["leaf.001"]: THREE.MeshStandardMaterial;
    ["wood_black.001"]: THREE.MeshStandardMaterial;
    pole_wood: THREE.MeshStandardMaterial;
    Blue: THREE.MeshStandardMaterial;
    black: THREE.MeshStandardMaterial;
    red: THREE.MeshStandardMaterial;
    blue: THREE.MeshStandardMaterial;
    sand: THREE.MeshStandardMaterial;
    leaf_black: THREE.MeshStandardMaterial;
  };
};

export function Park(props: React.JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/model/park.glb",
  ) as unknown as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.field.geometry}
        material={materials.field}
        position={[0, 0.347, 0]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={[-35.527, -0.02, -35.527]}
      />
      <group position={[28.147, 6.655, -28.219]} scale={[1.903, 1.975, 1.903]}>
        <mesh geometry={nodes.Sphere003_1.geometry} material={materials.leaf} />
        <mesh
          geometry={nodes.Sphere003_2.geometry}
          material={materials.wood_black}
        />
      </group>
      <group
        position={[-31.37, 4.962, -28.436]}
        rotation={[0, 0.767, 0]}
        scale={[1.984, 2.06, 1.984]}
      >
        <mesh geometry={nodes.Sphere005.geometry} material={materials.leaf} />
        <mesh
          geometry={nodes.Sphere005_1.geometry}
          material={materials.wood_black}
        />
      </group>
      <group
        position={[-30.29, 6.713, 33.086]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={[1.891, 1.963, 1.891]}
      >
        <mesh geometry={nodes.Sphere006.geometry} material={materials.leaf} />
        <mesh
          geometry={nodes.Sphere006_1.geometry}
          material={materials.wood_black}
        />
      </group>
      <group
        position={[32.358, 4.962, 33.055]}
        rotation={[Math.PI, -0.767, Math.PI]}
        scale={[1.422, 1.476, 1.422]}
      >
        <mesh geometry={nodes.Sphere007.geometry} material={materials.leaf} />
        <mesh
          geometry={nodes.Sphere007_1.geometry}
          material={materials.wood_black}
        />
      </group>
      <group
        position={[-23.74, 4.962, -29.324]}
        rotation={[Math.PI, -1.213, Math.PI]}
        scale={[1.422, 1.476, 1.422]}
      >
        <mesh
          geometry={nodes.Sphere008.geometry}
          material={materials["leaf.001"]}
        />
        <mesh
          geometry={nodes.Sphere008_1.geometry}
          material={materials["wood_black.001"]}
        />
      </group>
      <mesh
        geometry={nodes.wood_poles.geometry}
        material={materials.pole_wood}
        position={[0.344, 2.29, 13.877]}
        scale={[0.15, 1, 0.15]}
      />
      <group
        position={[-30.187, 4.962, 27.444]}
        rotation={[-Math.PI, 0.961, -Math.PI]}
        scale={[1.422, 1.476, 1.422]}
      >
        <mesh geometry={nodes.Sphere009.geometry} material={materials.leaf} />
        <mesh
          geometry={nodes.Sphere009_1.geometry}
          material={materials.wood_black}
        />
      </group>
      <group
        position={[-25.776, 4.962, 30.624]}
        rotation={[0, 0.837, 0]}
        scale={[1.422, 1.476, 1.422]}
      >
        <mesh geometry={nodes.Sphere010.geometry} material={materials.leaf} />
        <mesh
          geometry={nodes.Sphere010_1.geometry}
          material={materials.wood_black}
        />
      </group>
      <group
        position={[30.922, 6.475, 27.823]}
        rotation={[-Math.PI, 0.024, -Math.PI]}
        scale={[1.799, 1.867, 1.799]}
      >
        <mesh geometry={nodes.Sphere011.geometry} material={materials.leaf} />
        <mesh
          geometry={nodes.Sphere011_1.geometry}
          material={materials.wood_black}
        />
      </group>
      <group
        position={[32.769, 4.962, 16.027]}
        rotation={[0, -1.111, 0]}
        scale={[1.422, 1.476, 1.422]}
      >
        <mesh geometry={nodes.Sphere012.geometry} material={materials.leaf} />
        <mesh
          geometry={nodes.Sphere012_1.geometry}
          material={materials.wood_black}
        />
      </group>
      <group
        position={[18.306, 4.962, 32.644]}
        rotation={[Math.PI, -0.34, Math.PI]}
        scale={[1.422, 1.476, 1.422]}
      >
        <mesh geometry={nodes.Sphere013.geometry} material={materials.leaf} />
        <mesh
          geometry={nodes.Sphere013_1.geometry}
          material={materials.wood_black}
        />
      </group>
      <group
        position={[22.575, 4.962, -30.038]}
        rotation={[Math.PI, -1.41, Math.PI]}
        scale={[1.495, 1.551, 1.495]}
      >
        <mesh geometry={nodes.Sphere014.geometry} material={materials.leaf} />
        <mesh
          geometry={nodes.Sphere014_1.geometry}
          material={materials.wood_black}
        />
      </group>
      <group position={[4.802, 4.109, -26.599]} scale={[0.072, 2.532, 0.072]}>
        <mesh
          geometry={nodes.Cylinder025.geometry}
          material={nodes.Cylinder025.material}
        />
        <mesh
          geometry={nodes.Cylinder025_1.geometry}
          material={materials.Blue}
        />
      </group>
      <mesh
        geometry={nodes.Torus.geometry}
        material={materials.black}
        position={[-27.958, 0.545, -21.141]}
        rotation={[0, 0, -1.553]}
        scale={0.725}
      />
      <mesh
        geometry={nodes.Torus001.geometry}
        material={materials.red}
        position={[-26.114, 0.545, -19.186]}
        rotation={[0, 0, -1.553]}
        scale={0.725}
      />
      <mesh
        geometry={nodes.Torus002.geometry}
        material={materials.blue}
        position={[-29.467, 0.545, -17.31]}
        rotation={[0, 0, -1.553]}
        scale={0.725}
      />
      <mesh
        geometry={nodes.Cube.geometry}
        material={nodes.Cube.material}
        position={[-21.455, -0.051, 22.127]}
        scale={[5.79, 0.724, 5.79]}
      />
      <mesh
        geometry={nodes.Plane.geometry}
        material={materials.sand}
        position={[-21.563, 0.518, 22.101]}
        scale={5.15}
      />
      <mesh
        geometry={nodes.Sphere.geometry}
        material={materials.leaf_black}
        position={[-34.036, 0.835, 5.141]}
        rotation={[0, 1.528, 0]}
        scale={[2.311, 1.225, 1.225]}
      />
      <mesh
        geometry={nodes.Sphere020.geometry}
        material={materials.leaf_black}
        position={[-5.426, 0.935, 34.882]}
        rotation={[0, 1.528, 0]}
        scale={[1.441, 1.225, 1.224]}
      />
      <mesh
        geometry={nodes.Sphere001.geometry}
        material={materials.leaf_black}
        position={[4.421, 0.835, -33.733]}
        rotation={[-Math.PI, 0.043, -Math.PI]}
        scale={[2.311, 1.225, 1.225]}
      />
      <mesh
        geometry={nodes.Sphere002.geometry}
        material={materials.leaf_black}
        position={[34.965, 0.835, -3.745]}
        rotation={[Math.PI, -1.528, Math.PI]}
        scale={[2.311, 1.225, 1.225]}
      />
      <mesh
        geometry={nodes.Sphere003.geometry}
        material={materials.leaf_black}
        position={[-3.492, 0.835, 35.129]}
        rotation={[0, -0.043, 0]}
        scale={[2.311, 1.225, 1.225]}
      />
      <mesh
        geometry={nodes.Sphere004.geometry}
        material={materials.leaf_black}
        position={[5.694, 0.935, 35.285]}
        rotation={[0, 1.528, 0]}
        scale={[1.441, 1.225, 1.224]}
      />
    </group>
  );
}

useGLTF.preload("/model/park.glb");
